theme: jekyll-theme-minimal
title: Hongbo Ye
description: Research Assistant Professor, Department of Electrical Engineering, Hong Kong Polytechnic University
plugins:
  - jemoji
  
owner:
  name: Hongbo Ye
#  avatar: bio-photo.jpg
#  bio: "This is a sample Jekyll academic website."
#  email: 
  orcid: 0000-0001-9446-8787
  researchgate: hongbo_ye
  google:
    scholar: 6LrbJcYAAAAJ&hl
