# theme: jekyll-theme-minimal
theme: minimal-mistakes-jekyll
title: Hongbo Ye
description: Research Assistant Professor, Department of Electrical Engineering, Hong Kong Polytechnic University
#plugins:
#  - jemoji
  
orcid: 0000-0001-9446-8787
researchgate: hongbo_ye
googlescholar: 6LrbJcYAAAAJ&hl
